#!/bin/bash

#arguments are as follows: fake router ip, real router ip 

###Enable port forwarding
firewall $ echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward

###Forwarding rules applied Here!
##Initial Rule Forwards all traffic:
##if I understand this correctly we should be sorting on traffic headed to the attacker address.

iptables -A FORWARD -i etho0 -d $1 -j ACCEPT

iptables -A PREROUTING -d $1 -j DNAT --to-destination $2


